/*
 * led.c
 *
 *  Created on: May 2, 2023
 *      Author: ataha
 */
#include "stm32f4xx_hal.h"

void led_init(void){
	RCC->AHB1ENR |=RCC_AHB1ENR_GPIODEN;

	GPIOD->MODER |=GPIO_MODER_MODE12_0;
	GPIOD->MODER &=~(GPIO_MODER_MODE12_1);

	GPIOD->OTYPER &=~(GPIO_OTYPER_OT12);

	GPIOD->OSPEEDR &=~(GPIO_OSPEEDER_OSPEEDR12_0);
	GPIOD->OSPEEDR &=~(GPIO_OSPEEDER_OSPEEDR12_1);

	GPIOD->PUPDR &=~(GPIO_PUPDR_PUPD12_0);
	GPIOD->PUPDR &=~(GPIO_PUPDR_PUPD12_1);
}
void button_init(void){
	RCC->AHB1ENR |=RCC_AHB1ENR_GPIOAEN;

	GPIOA->MODER &=~(GPIO_MODER_MODE0_0);
	GPIOA->MODER &=~(GPIO_MODER_MODE0_1);

	GPIOA->PUPDR &=~(GPIO_PUPDR_PUPD0_0);
	GPIOA->PUPDR &=~(GPIO_PUPDR_PUPD0_1);
}

void exti_init(void){
	RCC->APB2ENR |=RCC_APB2ENR_SYSCFGEN;
	SYSCFG->EXTICR[0] |=SYSCFG_EXTICR1_EXTI0_PA;

	EXTI->IMR |=EXTI_IMR_IM0;
	//EXTI->FTSR |EXTI_FTSR_TR0;
	EXTI->RTSR |=EXTI_RTSR_TR0;

	NVIC_SetPriority(EXTI0_IRQn,3);
	NVIC_EnableIRQ(EXTI0_IRQn);
}

void led_ON(void){
	GPIOD->ODR |=GPIO_ODR_OD12;
	HAL_Delay(50);
	GPIOD->ODR &=~(GPIO_ODR_OD12);
	HAL_Delay(50);
}

